CREATE TABLE DB_THING
(
    ID bigint primary key,
    UUID VARCHAR(250) not null,
    NAME VARCHAR(250) not null
);

CREATE SEQUENCE DB_THING_SEQUENCE INCREMENT BY 50 START WITH 1000000 NO CYCLE;
CREATE INDEX ON DB_THING (UUID);